[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "RGS"
version = "0.1.0"
authors = [
    { name="Your Name", email="your.email@example.com" },
]
description = "Random Greedy Selection for feature selection"
requires-python = ">=3.8"